version: "3.9"

services:
  backend:
    build:
      context: ./Backend
    container_name: iglesia-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./Frontend
    container_name: iglesia-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
    depends_on:
      - backend
